//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALTER~COMMENT ON~CREATE~DROP~FLASHBACK~PURGE~TRUNCATE")]
        public string DDLSTM {
            get {
                return ((string)(this["DDLSTM"]));
            }
            set {
                this["DDLSTM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"CLUSTER~CONSTRAINT~DATABASE LINK~TRIGGER~DIMENSION~LIBRARY~TABLE~INDEX~INDEXTYPES~JAVA CLASS~JAVA RESOURCE~JAVA SOURCE~MATERIALIZED VIEW~MATERIALIZED VIEW LOG~TYPE~OPERATOR~PACKAGE~SEQUENCE~FUNCTION~PROCEDURE~SYNONYM~TABLE~VIEW~CONTEXT~DIRECTORY~PFILE~SPFILE~PROFILE~ROLE~ROLLBACK SEGMENT~TABLESPACE~USER")]
        public string ORAOBJ {
            get {
                return ((string)(this["ORAOBJ"]));
            }
            set {
                this["ORAOBJ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CALL~FROM~INTO~LOCK TABLE~MERGE~JOIN~INTO~UPDATE")]
        public string DMLSTM {
            get {
                return ((string)(this["DMLSTM"]));
            }
            set {
                this["DMLSTM"] = value;
            }
        }
    }
}
